- task: DotNetCoreCLI@2
  displayName: Restore API
  inputs:
    command: restore
    projects: 'WMS.API/WMS.API.csproj'

- task: DotNetCoreCLI@2
  displayName: Build API
  inputs:
    command: build
    projects: 'WMS.API/WMS.API.csproj'
    arguments: '--configuration $(buildConfiguration)'