trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:

# ==========================================
# BUILD BACKEND
# ==========================================

- stage: BuildBackend
  displayName: Build Backend

  jobs:

  - job: BuildAPI
    displayName: Build ASP.NET Core API

    steps:

    - task: UseDotNet@2
      displayName: Install .NET 8 SDK
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: dotnet --info
      displayName: Verify .NET SDK

    - task: DotNetCoreCLI@2
      displayName: Restore API
      inputs:
        command: 'restore'
        projects: 'WMS.API/WMS.API.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build API
      inputs:
        command: 'build'
        projects: 'WMS.API/WMS.API.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish API
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'WMS.API/WMS.API.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'

    - task: PublishBuildArtifacts@1
      displayName: Publish API Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'api'

# ==========================================
# BUILD FRONTEND
# ==========================================

- stage: BuildFrontend
  displayName: Build Frontend
  dependsOn: BuildBackend

  jobs:

  - job: AngularBuild
    displayName: Build Angular

    steps:

    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: '20.x'

    - script: |
        cd WMS.Frontend
        npm install
      displayName: Install NPM Packages

    - script: |
        cd WMS.Frontend
        npm run build -- --configuration production
      displayName: Build Angular

    - task: PublishBuildArtifacts@1
      displayName: Publish Frontend Artifact
      inputs:
        PathtoPublish: 'WMS.Frontend/dist'
        ArtifactName: 'frontend'